<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Escuela [
<!ELEMENT Escuela (id, nombreDeLaEscuela, fundacion, Superheroes*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombreDeLaEscuela (#PCDATA)>
<!ELEMENT fundacion (#PCDATA)>
<!ELEMENT Superheroes (id, Escuela, imagen, nombreSuperheroe, edad, numeroIdentificacion, poderes?)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT nombreSuperheroe (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT numeroIdentificacion (#PCDATA)>
<!ELEMENT poderes (#PCDATA)>

]>
<Escuela>
    <id>E1</id>
    <nombreDeLaEscuela>Escuela de Superheroes</nombreDeLaEscuela>
    <fundacion>2020</fundacion>
    <Superheroes>
        <id>S1</id>
        <Escuela>E1</Escuela>
        <imagen>https://upload.wikimedia.org/wikipedia/en/d/d6/Superman_Man_of_Steel.jpg</imagen>
        <nombreSuperheroe>SUPERMAN</nombreSuperheroe>
        <edad>32</edad>
        <numeroIdentificacion>12345</numeroIdentificacion>
    </Superheroes>
    <Superheroes>
        <id>S2</id>
        <Escuela>E1</Escuela>
        <imagen>https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/35/IronMan-EndgameProfile.jpg/revision/latest/scale-to-width-down/1000?cb=20190423175213</imagen>
        <nombreSuperheroe>IRON MAN</nombreSuperheroe>
        <edad>40</edad>
        <numeroIdentificacion>67890</numeroIdentificacion>
    </Superheroes>
    <Superheroes>
        <id>S3</id>
        <Escuela>E1</Escuela>
        <imagen>https://www.refinery29.com/images/8987954.jpg?format=webp&width=340&height=408&quality=85</imagen>
        <nombreSuperheroe>WONDER WOMAN</nombreSuperheroe>
        <edad>500</edad>
        <poderes>Lazo de la verdad, fuerza sobrehumana, vuelo</poderes>
        <numeroIdentificacion>54321</numeroIdentificacion>
    </Superheroes>
    <Superheroes>
        <id>S4</id>
        <Escuela>E1</Escuela>
        <imagen>https://insidethemagic.net/wp-content/uploads/2022/03/amazing-spider-man-800x400.jpg</imagen>
        <nombreSuperheroe>SPIDER-MAN</nombreSuperheroe>
        <edad>20</edad>
        <poderes>Agilidad, fuerza proporcional de aranya, sentido aracnido</poderes>
        <numeroIdentificacion>09876</numeroIdentificacion>
    </Superheroes>
</Escuela>